### ISSUE TITLE
Parking assistance

### ISSUE THREAD

**Issue by TobiasBanck** [DIT112-V19/group-11#16]
user story: 
-As a driver I want a parking sensor so that I can safely park the car 

Acceptance criteria:
-Parking sensor detects the object 
-The car plays a warning beep when on course of collusion with any object
-Warning sound becomes more frequent when getting closer to the object
-show error message to driver if sensor not recieving any signal

**Comment by Wagajay** [comment]
Acceptance Criteria.
Scenario : while moving in or out of parking zone
Given : The car is parked or parking
When: The car senses obstacles in the way
Then: The car should send a warning beep when on course of collusion with any object

**Comment by kentedstrom** [comment]
Decided not to implement.
