### ISSUE TITLE
Panel indicating distance back and front

### ISSUE THREAD

**Issue by TobiasBanck** [DIT112-V19/group-11#17]
User story.
As a driver I would like to see the distance between my car and objects so that I don't crash into them.

Acceptance Criteria:
Detect objects at the front and back of the car.
Display distance between the objects and the car on the console
Display error massage in case of sensor miss functionality on the console.

**Comment by TobiasBanck** [comment]
[Requirement #4 ](https://github.com/DIT112-V19/group-11/wiki/SmartCar-Requirements)

**Comment by Wagajay** [comment]
Acceptance Criteria:
Detect objects at the front and back of the car.
Display distance between the objects and the car on the console.

**Comment by kentedstrom** [comment]
Done.
