### ISSUE TITLE
Speedometer panel 

### ISSUE THREAD

**Issue by TobiasBanck** [DIT112-V19/group-11#7]

**Comment by simonjohansson1993** [comment]
user story:
As a driver I want a panel indicating speed of the car so that I can know how fast i'm going

Acceptance criteria:
Read speed of car.
Display speed of the car at the console.
Display error message if speed is not read

**Comment by sputtnick93** [comment]
> _No description provided._

**Comment by Wagajay** [comment]
Scenario: While the car is driving at a high speed
Given:The speed is above the limit
When: The car should be able to detect and calculate the speed
Then: Display the speed readings and a warning "above speed limit" on the speed meter
